In [ ]:
#Linear regression

In [1]:
#HOUSE PRICE PREDICTION BASED ON HOUSE SIZE
from sklearn.linear_model import LinearRegression

# House size
X = [[1000], [1200], [1500], [1800]]

# House price (in lakh)
y = [40, 50, 65, 80]

model = LinearRegression()
model.fit(X, y)

prediction = model.predict([[1600]])

print("Predicted Price:", prediction[0], "Lakh")

Predicted Price: 70.0 Lakh


In [3]:
#Student Marks Prediction
from sklearn.linear_model import LinearRegression

# Study Hours
X = [[2], [4], [6], [8]]

# Marks
y = [35, 50, 65, 80]

model = LinearRegression()
model.fit(X, y)

prediction = model.predict([[7]])

print("Predicted Marks:", prediction[0])

Predicted Marks: 72.5


In [4]:
#Employee Salary Prediction
from sklearn.linear_model import LinearRegression

# Years of Experience
X = [[1], [3], [5], [7]]

# Salary (in Rupees)
y = [25000, 40000, 60000, 80000]

model = LinearRegression()
model.fit(X, y)

prediction = model.predict([[6]])

print("Predicted Salary: ₹", prediction[0])

Predicted Salary: ₹ 69750.0


In [5]:
#Electricity Bill Prediction
from sklearn.linear_model import LinearRegression

# Electricity Units Consumed
X = [[100], [200], [300], [400]]

# Electricity Bill (in Rupees)
y = [600, 1200, 1800, 2400]

model = LinearRegression()
model.fit(X, y)

prediction = model.predict([[250]])

print("Predicted Electricity Bill: ₹", prediction[0])

Predicted Electricity Bill: ₹ 1500.0


In [6]:
#Crop Yield Prediction
from sklearn.linear_model import LinearRegression

# Fertilizer Used (kg)
X = [[10], [20], [30], [40]]

# Crop Yield (kg)
y = [1000, 1500, 2000, 2500]

model = LinearRegression()
model.fit(X, y)

prediction = model.predict([[25]])

print("Predicted Crop Yield:", prediction[0], "kg")

Predicted Crop Yield: 1750.0 kg


In [7]:
#Fuel Consumption Prediction
from sklearn.linear_model import LinearRegression

# Distance Travelled (km)
X = [[50], [100], [150], [200]]

# Fuel Consumed (litres)
y = [3, 6, 9, 12]

model = LinearRegression()
model.fit(X, y)

prediction = model.predict([[120]])

print("Predicted Fuel Consumption:", prediction[0], "litres")

Predicted Fuel Consumption: 7.199999999999999 litres


In [ ]:
#K-Means Clustering

In [2]:
from sklearn.cluster import KMeans
import numpy as np

data = np.array([
    [2, 3],
    [3, 4],
    [10, 12],
    [11, 13]
])

model = KMeans(n_clusters=2, random_state=42)
model.fit(data)

print("Cluster Labels:")
print(model.labels_)


/lib/python3.14/site-packages/threadpoolctl.py:1135: RuntimeWarning: JsProxy.as_object_map() is deprecated. Use as_py_json() instead.
  for filepath in LDSO.loadedLibsByName.as_object_map():


Cluster Labels:
[0 0 1 1]


In [8]:
#Customer Shopping Clustering 
from sklearn.cluster import KMeans
import numpy as np

# Age, Monthly Spending (₹)
data = np.array([
    [20, 5000],
    [22, 6000],
    [45, 30000],
    [50, 35000]
])

model = KMeans(n_clusters=2, random_state=42)
model.fit(data)

print("Cluster Labels:")
print(model.labels_)

Cluster Labels:
[0 0 1 1]


In [11]:
#Hospital Patients 
from sklearn.cluster import KMeans
import numpy as np

data = np.array([
    [25, 110],
    [70, 170],
    [30, 115],
    [65, 165],
    [68, 160],
    [72, 175]
])

model = KMeans(n_clusters=2, random_state=42)
model.fit(data)

print("Cluster Labels:")
print(model.labels_)

Cluster Labels:
[0 1 0 1 1 1]


In [10]:
#Mobile Phone Usage Clustering 
from sklearn.cluster import KMeans
import numpy as np

# Screen Time (hours), Daily Data Usage (GB)
data = np.array([
    [2, 1],
    [3, 2],
    [8, 8],
    [9, 10]
])

model = KMeans(n_clusters=2, random_state=42)
model.fit(data)

print("Cluster Labels:")
print(model.labels_)

Cluster Labels:
[0 0 1 1]


In [12]:
#Gym Members 
from sklearn.cluster import KMeans
import numpy as np

data = np.array([
    [1, 200],
    [2, 250],
    [5, 700],
    [6, 850],
    [7, 900],
    [3, 300]
])

model = KMeans(n_clusters=2, random_state=42)
model.fit(data)

print("Cluster Labels:")
print(model.labels_)

Cluster Labels:
[1 1 0 0 0 1]
