In [2]:
class Student:
    pass
s1 = Student()

In [3]:
class Student:
   def __init__(self, name, age):
          self.name = name
          self.age = age

s1 = Student("Rahul",20)
s2 = Student("Priya",22)

In [5]:
class Student:
   def __init__(self):
       print("Object Created")
s = Student()


Object Created


In [6]:
class Student:
     def study(self):
        print("Student is studying")

s1=Student()
s1.study()

Student is studying


In [7]:
class Student:
    name = "Aman"
    age = 20
    marks = 90

student1 = Student()

print("Name:", student1.name)
print("Age:", student1.age)
print("Marks:", student1.marks)

Name: Aman
Age: 20
Marks: 90


In [8]:

class Student:

    def __init__(self, name, age, marks):
        self.name = name
        self.age = age
        self.marks = marks

student1 = Student("Aman", 20, 95)

print("Name:", student1.name)
print("Age:", student1.age)
print("Marks:", student1.marks)

Name: Aman
Age: 20
Marks: 95


In [9]:
class Calculator:

    def add(self, a, b):
        return a + b

    def multiply(self, a, b):
        return a * b


obj = Calculator()

print("Addition:", obj.add(10, 20))
print("Multiplication:", obj.multiply(5, 6))

Addition: 30
Multiplication: 30


In [10]:
class Animal:

    def sound(self):
        print("Animal makes sound")


class Dog(Animal):

    def bark(self):
        print("Dog barks")


d = Dog()

d.sound()
d.bark()

Animal makes sound
Dog barks


In [11]:
class Person:

    def __init__(self, name):
        self.name = name

class Student(Person):

    def display(self):
        print("Student Name:", self.name)

s = Student("Aman")

s.display()

Student Name: Aman


In [12]:
class Father:

    def skill1(self):
        print("Driving")

class Mother:

    def skill2(self):
        print("Cooking")

class Child(Father, Mother):

    def skill3(self):
        print("Programming")

c = Child()

c.skill1()
c.skill2()
c.skill3()

Driving
Cooking
Programming


In [16]:
pip install numpy

<class 'OSError'>: Not available

In [17]:
import numpy as np

print(np.__version__)

2.4.3


In [22]:
import numpy as np
a = np.array([10,20,30,40])
print(a)

[10 20 30 40]


In [23]:
a = np.array([1.2,2.5,3.8])
print(a)

[1.2 2.5 3.8]


In [24]:
a = np.array(["Apple","Mango","Banana"])
print(a)

['Apple' 'Mango' 'Banana']


In [25]:
#1D
a = np.array([10,20,30,40])
print(a)

[10 20 30 40]


In [26]:
#2D
a = np.array([
[1,2,3],
[4,5,6]
])
print(a)

[[1 2 3]
 [4 5 6]]


In [27]:
#3D
a = np.array([
[[1,2],[3,4]],
[[5,6],[7,8]]
])
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
#Array dimension
a = np.array([1,2,3])
print(a.ndim)

1


In [29]:
#2D
a = np.array([[1,2],[3,4]])
print(a.ndim)

2


In [30]:
#Shape of Array
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [31]:
#Size of Array
a = np.array([[1,2],[3,4]])
print(a.size)


4


In [32]:
#Data Type
a = np.array([10,20,30])
print(a.dtype)

int32


In [33]:
#Array of Zeros
import numpy as np
a = np.zeros((3,4))
print(a)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [34]:
#Array of Ones
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [35]:
#Identity Matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [36]:
#Empty Array
a = np.empty((2,2))
print(a)

[[1. 1.]
 [1. 1.]]


In [37]:
#arange()
import numpy as np
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [38]:
#Step Value
a = np.arange(0,20,2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18]


In [39]:
#linspace()
a = np.linspace(1,10,5)
print(a)


[ 1.    3.25  5.5   7.75 10.  ]


In [44]:
#Reshaping Arrays
a=np.arange(6)
print(a)
[ 1, 2, 3,  4,  5,  6]
b=a.reshape(3,2)
print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [45]:
a=np.arange(6)
print(a)
[ 1, 2, 3,  4,  5,  6]
b=a.reshape(2,3)
print(b)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [46]:
a=np.array([[[1,2],[3,5]],[[1,7],[8,0]]])
print(a.flatten())

[1 2 3 5 1 7 8 0]


In [47]:
a=np.array([[[1,2],[3,5]],[[1,7],[8,0]]])
print(a[0])

[[1 2]
 [3 5]]


In [48]:
a=np.array([[[1,2],[3,5]],[[1,7],[8,0]]])
print(a[0][1])

[3 5]


In [49]:
a=np.array([[[1,2],[3,5]],[[1,7],[8,0]]])
print(a[0][1][0])

3


In [52]:
#Addition
a = np.array([10,20,30])
b = np.array([1,2,3])
print(a+b)

#Subtraction
print(a-b)

#Multiplication
print(a*b)

#Division
print(a/b)

#Square
print(a**2)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
[100 400 900]


In [53]:
a = np.array([1, 4, 9, 16])
np.abs(a) # Absolute value
np.sqrt(a) #sqrt
np.exp(a) # Exponential
np.log(a) # Natural log
np.sin(a) # Sine
np.cos(a) # Cosine
np.tan(a) # Tangent

array([ 1.55740772,  1.15782128, -0.45231566,  0.30063224])

In [54]:
marks = np.array([75,80,90,85,95])
#Average
print(np.mean(marks))
#Maximum
print(np.max(marks))
#Minimum
print(np.min(marks))
#Sum
print(np.sum(marks))
#Median
print(np.median(marks))
#Standard Deviation
print(np.std(marks))

85.0
95
75
425
85.0
7.0710678118654755


In [55]:
#Copy
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)


[1 2 3]
[100   2   3]


In [56]:
#View
a = np.array([1,2,3])
b = a.view()
b[0] = 100
print(a)
print(b)


[100   2   3]
[100   2   3]


In [57]:
#Random Numbers
import numpy as np
print(np.random.rand(5))
#Random integers
print(np.random.randint(1,100,10))
#Random matrix
print(np.random.randint(1,50,(3,4)))

[0.69747234 0.21024505 0.15336627 0.43267874 0.01535597]
[18 19 68 62 81 70 74 46  6 20]
[[37 40 28  6]
 [ 2 17 36 23]
 [ 2 11  2 35]]


In [58]:
#Boolean Filtering
marks = np.array([45,60,75,30,90])
print(marks[marks > 50])

[60 75 90]


In [59]:
import numpy as np
a = np.array([1,2,3])
print(a + 10)

[11 12 13]


In [60]:
matrix = np.array([[1,2],[3,4]])
print(matrix * 5)

[[ 5 10]
 [15 20]]
